# Generated by Django 3.1.4 on 2021-01-29 04:37

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_mylogin',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='date mylogin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='<br>必須．日本語でも大丈夫です.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='ユーザ名'),
        ),
    ]
